bucket         = "ic-dev-tf-statefile-storage"
profile        = "terraform"
key            = "ic-dev/terraform-statefile/terraform.tfstate"
region         = "us-east-1"
dynamodb_table = "ic-dev-lock-table"
encrypt        = true
